---
- hosts: cluster
  become: true
  gather_facts: False
  vars_files:
    - group_vars/all.yaml
  roles:
    - role: common

- hosts: master
  gather_facts: False
  become: true
  vars_files:
    - group_vars/all.yaml
    - group_vars/master.yaml
  roles:
    - role: master

- hosts: nodes
  gather_facts: False
  become: true
  vars_files:
    - group_vars/all.yaml
    - group_vars/nodes.yaml
  roles:
    - role: nodes
