- name: Download official Kubernetes 1.7.0 node binaries
  get_url:
    url: https://dl.k8s.io/v1.7.0/kubernetes-node-linux-amd64.tar.gz
    dest: /tmp/download
    checksum: sha256:6c6cece62bad5bfeaf4a4b14e93c9ba99c96dc82b7855a2214cdf37a65251de8
  async: '{{ file_async_wait }}'
  poll: '{{ file_poll_interval }}'

- name: Extracting and installing Kubernetes server binaries
  unarchive:
    src: /tmp/download/kubernetes-node-linux-amd64.tar.gz
    dest: /tmp/download
    copy: no

- command: >
    'mv /tmp/download/kubernetes/node/bin/{{ item }} /usr/local/kubernetes/bin/{{ item }}'
  with_items:
    - 'kube-proxy'
    - 'kubelet'
    - 'kubectl'
    - 'kubefed'

- file:
    src: '/usr/local/kubernetes/bin/{{ item }}'
    dest: '/usr/bin/{{ item }}'
    state: link
    # TODO: refactor this and eliminate duplication.
  with_items:
    - 'kube-proxy'
    - 'kubelet'
    - 'kubectl'
    - 'kubefed'

- file:
    path: /tmp/download/kubernetes/node
state: absent
