---
- name: Creating additional user groups
  group:
    name: '{{ item }}'
    state: present
  with_items:
    - 'docker'
    - 'kubernetes'

# This will reset ansible's connection so that the new created groups are
# available to the user
- meta: reset_connection

- name: Creating a default user 'kube' for system wide operations
  user:
    name: kube
    comment: 'Kubernetes system wide operation user'
    state: present
    password: '{{ kube_user_password }}'
    groups:
      - 'kubernetes'
      - 'docker'
    append: yes

- name: Updating system to the latest packages
  zypper:
    name: '*'
    state: latest
    update_cache: yes

- name: Installing additional packages
  zypper:
    name: '{{ item }}'
    state: latest
    type: package
  with_items:
    - 'ncat'
    - 'nmap'
    - 'wget'
    - 'curl'
    - 'tmux'
    - 'mlocate'
    - 'net-tools'
    - 'nload'
    - 'htop'

- name: Creating tmp kubernetes download folder
  file:
    path: '{{ item }}'
    state: directory
    mode: 0755
  with_items:
    - '/tmp/download/helm'

    - '/usr/local/docker/bin'
    - '/usr/local/kubernetes/bin'
    - '/usr/local/etcd/bin'

    - '/etc/docker'
    - '/etc/kubernetes'
    - '/etc/etcd'

- include: docker.yaml
- include: etcd.yaml
